@startuml
skinparam componentStyle uml2

actor User

package "Service UI" {

    component "Web Server"

    Component "Web Interface"

}

[Service Datastore] <- [Web Interface] : "REST API"
[Web Interface] -> [Web Server] : "REST API"

User --> [Web Interface] : "Web Browser"

legend 
    Arrows point from the depending elements to those they depend on.
endlegend

@enduml