@startuml
skinparam componentStyle uml2

participant "User\n(Web Browser)" as User

participant "Web App"
participant "Datastore"
participant "Web Server"

"Web Server" -> "Web App" : Publish Web App at URL
activate "Web Server"
activate "Web App"

User -> "Web App" : Request Website\nfrom URL
activate User
"Web App" -> User : Send Website
"Web App" -> "Web Server" : Request API Endpoint\nfor Datastore (GET)
"Web Server" -> "Web App" : API Endpoint (JSON)

"Web App" -> "Datastore" : Request Data for given\nTime Interval (GET)
activate Datastore
"Datastore" -> "Web App" : Send Data (JSON)
deactivate Datastore

"Web App" -> User : Update Chart





@enduml