@startuml
skinparam componentStyle uml2

package "Service Datastore" {

    database "DB"

    component "Business Logic"

    [Business Logic] --> DB : "SQLite"

}

() "public"
(public) -> [Business Logic] : "REST API"

legend 
    Arrows point from the depending elements to those they depend on.
endlegend

@enduml