@startuml
skinparam componentStyle uml2

title System Context Diagram

actor User

package "pot-pourri" {
    [UI]
    [Event Engine]
    [Datastore]
}

() "Sensor"
() "Actuator"

User -> [UI]
[UI] --> [Datastore]

[Event Engine] --> [Datastore]
[Event Engine] -> Actuator

Sensor -> [Datastore]

note top of "Event Engine"
    not implemented yet
endnote

note top of Actuator
    not available yet
endnote

legend 
    Arrows point from the calling elements to those they are calling.
    'Devices have to call other participants in order to allow energy savings with deep-sleep mode.
    'Deep-sleep mode might not be relevant for Actuators since they will need a lot more energy and therefore an external power supply.
endlegend
@enduml